# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import gradio as gr
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "tiiuae/falcon-7b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype=torch.float16)
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

def get_prompt(figure, question):
  prompts = {
        "Atatürk": f"""
You are Mustafa Kemal Atatürk, founder of modern Turkey.
Speak as a rational, visionary leader with clarity, determination, and deep knowledge of history and reform.

User: {question}
Atatürk:""",

        "Shakespeare": f"""
You are William Shakespeare.
Respond with poetic elegance, Early Modern English flair, and literary depth.

User: {question}
Shakespeare:""",

        "Cleopatra": f"""
You are Cleopatra, Queen of Egypt.
Speak with regal confidence, intelligence, and diplomatic charm, reflecting the power and mystery of ancient Egypt.

User: {question}
Cleopatra:""",

        "Einstein": f"""
You are Albert Einstein.
Respond with scientific insight, philosophical curiosity, and a gentle tone of a wise thinker.

User: {question}
Einstein:""",

        "Socrates": f"""
You are Socrates, the classical Greek philosopher.
Use the Socratic method—answer questions with questions and provoke critical thinking.

User: {question}
Socrates:"""
    }

  return prompts.get(figure, f"You are {figure}. User: {question}\n{figure}:")

def chat(question, figure):
  prompt = get_prompt(figure, question)
  output = generator(prompt, max_new_tokens=200, temperature=0.8)[0]["generated_text"]
  return output.split(f"{figure}:")[-1].strip()


custom_html = """
<div style='text-align: center; padding20px; background-color: #f2f2f2; border-radius: 12px;'>
  <h1 style='color: #333;'>🕰️ Talk to History</h1>
  <p style='font-size: 16px; color: #555;'>
        Ask a question and receive an answer from a legendary historical figure.<br>
        Choose among Atatürk, Shakespeare, Cleopatra, Einstein, or Socrates.<br>
        The answers are generated using an open-source AI model with custom personas.
  </p>
</div>
"""


# === GRADIO UI ===
figures = ["Atatürk", "Shakespeare", "Cleopatra", "Einstein", "Socrates"]

with gr.Blocks() as demo:
  gr.HTML(custom_html)

  with gr.Row():
    question = gr.Textbox(label="Your Question", placeholder="e.g., What is the purpose of the education?")
    figure = gr.Dropdown(choices=figures, label="Choose a Histori Figure")

  output = gr.Textbox(label="Response", lines=6)

  gr.Button("Ask").click(chat, inputs=[question, figure], outputs=output)